# Generated by Django 4.1.7 on 2023-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Frequency', models.CharField(max_length=10)),
                ('Cores', models.IntegerField()),
                ('Memory_type', models.CharField(max_length=4)),
                ('Max_RAM_frequency', models.IntegerField()),
                ('Graphics_core', models.CharField(default=None, max_length=40)),
                ('Heat_dissipation', models.IntegerField()),
                ('Photo', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
