# Generated by Django 4.1.7 on 2023-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0002_processor_socket_alter_processor_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processor',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
