# Generated by Django 4.1.7 on 2023-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0003_processor_price_alter_processor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='Graphics_core',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='processor',
            name='Photo',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='Socket',
            field=models.CharField(choices=[('AM4', 'AM4'), ('AM3+', 'AM3+'), ('AM5', 'AM5'), ('LGA 1151', 'LGA 1151'), ('LGA 1200', 'LGA 1200'), ('LGA 1700', 'LGA 1700'), ('LGA 2066', 'LGA 2066')], default='LGA 1151', max_length=8),
        ),
    ]
