# Generated by Django 4.1.7 on 2023-03-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0004_alter_processor_graphics_core_alter_processor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='Photo',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
