# Generated by Django 4.1.7 on 2023-03-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0008_allmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PC_Configurator.processor')),
            ],
        ),
        migrations.DeleteModel(
            name='AllModels',
        ),
    ]
