# Generated by Django 4.1.7 on 2023-03-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0009_add_processor_delete_allmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_processor',
        ),
    ]
