# Generated by Django 4.1.7 on 2023-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0013_remove_add_processor_cores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, verbose_name='Наименоваие')),
                ('Socket', models.CharField(choices=[('AM4', 'AM4'), ('AM3+', 'AM3+'), ('AM5', 'AM5'), ('LGA 1151', 'LGA 1151'), ('LGA 1200', 'LGA 1200'), ('LGA 1700', 'LGA 1700'), ('LGA 2066', 'LGA 2066')], default='LGA 1151', max_length=8, verbose_name='Сокет')),
                ('Chipset', models.CharField(max_length=20, verbose_name='Чипсет')),
                ('Memory_type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=4, verbose_name='Тип памяти')),
                ('Max_RAM_frequency', models.IntegerField(verbose_name='Максимальная частота оперативки')),
                ('PCI_slot', models.CharField(max_length=10, verbose_name='Слоты PCI')),
                ('Size', models.CharField(max_length=15, verbose_name='Размер')),
                ('Photo', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Материская плата',
                'verbose_name_plural': 'Материнские платы',
                'ordering': ('Name',),
            },
        ),
    ]
