# Generated by Django 4.1.7 on 2023-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0016_alter_motherboard_pci_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Socket', models.CharField(blank=True, max_length=8, null=True, verbose_name='Сокет')),
                ('Memory_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='Тип памяти')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('PCI_slot', models.CharField(default='PCI-Ex16', max_length=10, verbose_name='Слоты PCI')),
                ('Size', models.CharField(max_length=15, verbose_name='Размер')),
            ],
        ),
    ]
