# Generated by Django 4.1.7 on 2023-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0017_add_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, verbose_name='Наименоваие')),
                ('Memory', models.IntegerField(verbose_name='Количество памяти')),
                ('Type_memory', models.CharField(max_length=10, verbose_name='Тип памяти')),
                ('Connectors', models.TextField(verbose_name='Видеоразъемы')),
                ('PCI_slot', models.CharField(default='PCI-Ex16', max_length=10, verbose_name='Слоты PCI')),
                ('Bit', models.IntegerField(verbose_name='Разрядность')),
                ('Video_frequency', models.IntegerField(verbose_name='Частота работы видеочипа')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ('Name',),
            },
        ),
    ]
