# Generated by Django 4.1.7 on 2023-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0023_ram_photo_ram_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memory_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='Тип памяти')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
        ),
    ]
