# Generated by Django 4.1.7 on 2023-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0024_add_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Interface', models.CharField(default='SATA III', max_length=10, verbose_name='Интерфейс')),
                ('Bandwidth', models.IntegerField(verbose_name='Пропускная способность')),
                ('Speed', models.IntegerField(verbose_name='Скорость оборотов')),
                ('Cache', models.IntegerField(verbose_name='Кэш память')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Жесткий диск',
                'verbose_name_plural': 'Жесткие диски',
                'ordering': ('Name',),
            },
        ),
    ]
