# Generated by Django 4.1.7 on 2023-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0025_add_hdd_hdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Power', models.IntegerField(verbose_name='Мощность')),
                ('Base_connector', models.CharField(default='20 + 4 pin', max_length=15, verbose_name='Основной разъем питания')),
                ('Cpu_connector', models.IntegerField(default=4, verbose_name='Разъемы для питания процессора')),
                ('Sata_coonector', models.IntegerField(default=2, verbose_name='Количество SATA разъемов')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
                'ordering': ('Name',),
            },
        ),
    ]
