# Generated by Django 4.1.7 on 2023-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0027_add_powerblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=50, verbose_name='Материал')),
                ('Speed', models.IntegerField(verbose_name='Кол-во оборотов')),
                ('Power', models.IntegerField(verbose_name='Мощность')),
                ('Connector', models.IntegerField(verbose_name='Разъем подключения')),
                ('Noise', models.IntegerField(verbose_name='Уровень шума')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Кулер',
                'verbose_name_plural': 'Кулеры',
                'ordering': ('Name',),
            },
        ),
    ]
