# Generated by Django 4.1.7 on 2023-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0028_add_cooler_cooler'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Form', models.CharField(default='Micro-ATX', max_length=20, verbose_name='Максимальный форм фактор')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Form', models.CharField(default='Micro-ATX', max_length=20, verbose_name='Максимальный форм фактор')),
                ('USB', models.CharField(default='USB 2.0 Type-A', max_length=50, verbose_name='Юсб')),
                ('Color', models.CharField(default='Черный', max_length=20, verbose_name='Цвет')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ('Name',),
            },
        ),
    ]
