# Generated by Django 5.2 on 2025-04-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0029_add_case_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='Name',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='Name',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
