# Generated by Django 5.2 on 2025-04-16 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Configurator', '0030_alter_motherboard_name_alter_processor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.ManyToManyField(to='PC_Configurator.case')),
                ('coolers', models.ManyToManyField(to='PC_Configurator.cooler')),
                ('hdds', models.ManyToManyField(to='PC_Configurator.hdd')),
                ('motherboards', models.ManyToManyField(to='PC_Configurator.motherboard')),
                ('poweblocks', models.ManyToManyField(to='PC_Configurator.powerblock')),
                ('processors', models.ManyToManyField(to='PC_Configurator.processor')),
                ('rams', models.ManyToManyField(to='PC_Configurator.ram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videocards', models.ManyToManyField(to='PC_Configurator.videocard')),
            ],
        ),
    ]
